### PR TITLE
fix(plasma): Plasma Data Source Cleanup

### PR DESCRIPTION
**Pull request by refcell**
**Description**

Removes unused fields from the plasma data source.

Cleans up doc comments.

Uses the canonical block id constructor.

### CODE REVIEW

**Comment by refcell** [comment]
* **#164** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/kona/164?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @refcell and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by clabby — APPROVED** [review]

**Comment by clabby** [comment]
Actually, can we just put these changes in https://github.com/ethereum-optimism/kona/pull/165? Looks like these'll conflict on merge.

**Review by clabby — CHANGES_REQUESTED** [review]
^

**Review by clabby — APPROVED** [review]
solid!

**Pull request merged**
